db.users.drop();
db.users.insertMany([
    {
        _id: 'da3916f299434734b3ac4014a13d231e',
        email: 'giga.chad@hotmale.com',
        username: "giga.chad",
        name: "Giga",
        surname: "Chad",
        password: '123',
        birthday: "1970-01-01",
        gender: "Male",
        weight: 100,
        height: 220,
        hair_colour: 'Dark',
        eye_colour: 'Blue',
        bio: "I am chad",
        pfp: "default.jpg",
        type: "premium"
    },
    {
        _id: '2bb7bbf7e3174bdba8b26fc13f8f90c3',
        email: 'bog@hotmale.com',
        username: 'bog',
        name: 'Igor',
        surname: 'Bogdanoff',
        password: '123',
        birthday: "1949-08-29",
        gender: "Male",
        weight: 85,
        height: 180,
        hair_colour: 'Ginger',
        eye_colour: 'Brown',
        bio: 'I invest in cryptocurrency',
        pfp: "default.jpg",
        type: "free"
    },
    {
        _id: '82210c12f80b4532b1bc8e0d2ae2f163',
        email: 'harold@yahoo.com',
        username: 'harold',
        name: 'Harold',
        surname: 'Harold',
        password: '123',
        birthday: '1945-07-11',
        gender: "Male",
        weight: 70,
        height: 170,
        hair_colour: 'Dark',
        eye_colour: 'Blue',
        bio: 'Feel the pain',
        pfp: "default.jpg",
        type: "free"
    },
    {
        _id: '927fbcc9d7a8464c909da9b9e1117bb9',
        email: 'karolidis@uniwa.gr',
        username: 'karolidis',
        name: 'Dimitrios',
        surname: 'Karolidis',
        password: '123',
        birthday: '1970-01-01',
        gender: 'Male',
        weight: 80,
        height: 190,
        hair_colour: 'Dark',
        eye_colour: 'Green',
        bio: 'The best professor in ICE UNIWA',
        pfp: "default.jpg",
        type: 'free'
    },
    {
        _id: '6c3239dc59814111b60098393bf22cf6',
        email: 'mia@gmail.com',
        username: 'mia',
        name: 'Mia',
        surname: 'Wallace',
        password: '123',
        birthday: '2000-05-29',
        gender: 'Female',
        weight: 65,
        height: 170,
        hair_colour: 'Dark',
        eye_colour: 'Blue',
        bio: 'Why do we feel the need to yak about bs?',
        pfp: 'default.jpg',
        type: 'free'
    },
    {
        _id: 'c79932cbc58c4f8bbf1e49a4ac224250',
        email: 'the.bride@bill.com',
        username: 'the.bride',
        name: 'Beatrix',
        surname: 'Kiddo',
        password: '123',
        birthday: '1980-06-21',
        gender: 'Female',
        weight: 65,
        height: 170,
        hair_colour: 'Blonde',
        eye_colour: 'Blue',
        bio: 'It\'s Mercy, Compassion And Forgiveness I Lack. Not Rationality!',
        pfp: 'default.jpg',
        type: 'free'
    },
    {
        _id: '0efd901283714e59ad729dc66d80e670',
        email: 'jules@hotmale.com',
        username: 'jules',
        name: 'Jules',
        surname: 'Winnfield',
        password: '123',
        birthday: '1970-05-12',
        gender: 'Male',
        weight: 75,
        height: 200,
        hair_colour: 'Dark',
        eye_colour: 'Brown',
        bio: 'Royale with Cheese',
        pfp: 'default.jpg',
        type: 'free'
    },
    {
        _id: '53511fe0da8e43cb89e4dfec511d2cf9',
        email: 'andriana@soprano.com',
        username: 'andriana',
        name: 'Adriana',
        surname: 'La Cerva',
        password: '123',
        birthday: '1990-12-10',
        gender: 'Female',
        weight: 60,
        height: 175,
        hair_colour: 'Blonde',
        eye_colour: 'Brown',
        bio: 'ig: andriana_la_cerva',
        pfp: 'default.jpg',
        type: 'free'
    },
    {
        _id: 'a6f87bad71ff4b6fb679775555a1225c',
        email: 'scarlett@hotmail.com',
        username: 'scarlett',
        name: 'Scarlett',
        surname: 'Johnanson',
        password: '123',
        birthday: '1984-11-22',
        gender: 'Female',
        weight: 70,
        height: 180,
        hair_colour: 'Blonde',
        eye_colour: 'Green',
        bio: 'Natasha Romanov in the Avengers',
        pfp: 'default.jpg',
        type: 'free'
    },
    {
        _id: 'cf6993a1b4244d918de943c281732919',
        email: 'margot@hotmail.com',
        username: 'margot',
        name: 'Margot',
        surname: 'Robbie',
        password: '123',
        birthday: '1990-07-02',
        gender: 'Female',
        weight: 65,
        height: 170,
        hair_colour: 'Blonde',
        eye_colour: 'Blue',
        bio: 'Harley Quinn',
        pfp: 'default.jpg',
        type: 'free'
    }
]);