version: "3.8"

services:
  client:
    build: client
    container_name: tinder_client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/client
    environment:
      NODE_APP: client
      NODE_ENV: development
    links:
      - backend

  backend:
    build: backend
    container_name: tinder_api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    environment:
      FLASK_APP: app
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    links:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express_tinder
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: datinguser
      ME_CONFIG_MONGODB_ADMINPASSWORD: datinguserpasswd
    links:
      - mongo

  mongo:
    build: db
    container_name: mongodb_tinder
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: datinguser
      MONGO_INITDB_ROOT_PASSWORD: datinguserpasswd
      MONGO_INITDB_DATABASE: tinderClone
